spring.application.name=driver-vehicle-service
server.port=8082

# Independent Database Ownership: ridelink_driver_vehicle_db
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=ridelink_driver_vehicle_db
spring.data.mongodb.auto-index-creation=true

# Externalized JWT Settings
jwt.secret=${JWT_SECRET:RideLinkSuperSecretSecurityKey2026WithSufficientLengthForHS256Algorithm}

# Actuator Health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# OpenAPI & Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
