spring.application.name=ride-management-service
server.port=8083

# Independent Database Ownership: ridelink_ride_db
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_ride_db}
spring.data.mongodb.database=ridelink_ride_db
spring.data.mongodb.auto-index-creation=true

# Externalized JWT Settings
jwt.secret=${JWT_SECRET}

# Interservice Communication URLs
services.driver.base-url=${DRIVER_SERVICE_URL:http://localhost:8082}
services.fare.base-url=${FARE_SERVICE_URL:http://localhost:8084}

# Actuator Health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# OpenAPI & Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
